spring.application.name=invite service
spring.config.import=optional:file:.env[.properties]

server.port=${APPLICATION_PORT:3000}
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/scrumdapp}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DATABASE_USER:myuser}
spring.datasource.password=${DATABASE_PASSWORD:secret}

spring.jpa.properties.hibernate.jdbc.batch_size=20

spring.flyway.enabled=false
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}
spring.flyway.locations=classpath:db/migrations
spring.jpa.hibernate.ddl-auto=update