spring.application.name=invite service
spring.config.import=optional:file:.env[.properties]

server.port=${APPLICATION_PORT:3000}

safetycode.length=69
group.service.url=${GROUP_SERVICE_URL:http://localhost:3000}
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/scrumdapp}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DATABASE_USER:myuser}
spring.datasource.password=${DATABASE_PASSWORD:secret}

spring.jpa.properties.hibernate.jdbc.batch_size=20
passport.jwk-set-uri=${JWK_SET_URI}

spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.enabled=false