CREATE TABLE group_invites
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id      INTEGER                                  NOT NULL,
    token         VARCHAR(255)                             NOT NULL,
    password_hash VARCHAR(255)                             NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    expires_at    TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    is_active     BOOLEAN                                  NOT NULL,
    CONSTRAINT pk_group_invites PRIMARY KEY (id)
);

ALTER TABLE group_invites
    ADD CONSTRAINT uc_group_invites_token UNIQUE (token);